### ISSUE TITLE
Decide Topic

### ISSUE THREAD

**Issue by masonshuler** [masonshuler/CloudApp#1]
Leave comments on ideas for project.

**Comment by emcghee** [comment]
So he talks about either considering a solution to problem's that businesses have or people have. He also mentions later that we could make like a social network site. To kind of like come up with one each of these three categories I'd say we do: 

- implement like a shopping website for some random company and just have statistics available so that we can fill out more requirements,

- implement like a grading website like canvas,

- or implement our own version of facebook, this would help fulfill requirements like instant messenger between clients or something like that

What do you guys think?

**Comment by shuvesta** [comment]
I like our own version of facebook and a grading website like canvas. This is due tomorrow at 11 pm.

**Comment by masonshuler** [comment]
I think it would be cool to do like a Goodwill shopping website, it would
be pretty easy too bc of the list database already put in place

On Mar 12, 2018 2:49 PM, "shuvesta" <notifications@github.com> wrote:

I like our own version of facebook and a grading website like canvas. This
is due tomorrow at 11 pm.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/masonshuler/CloudApp/issues/1#issuecomment-372422424>,
or mute the thread

**Comment by emcghee** [comment]
Yeah I think that's a good point about the database, both the social media thing or canvas thing would be harder for the database.

**Comment by emcghee** [comment]
All we have to do is describe the problem, say why it's important, and then the Java EE features

**Comment by shuvesta** [comment]
Do we wanna make a google doc or do it on github?

**Comment by emcghee** [comment]
Let's do google doc, do we know everyone's email?

**Comment by masonshuler** [comment]
mshuler@vt.edu

On Mar 12, 2018 6:13 PM, "emcghee" <notifications@github.com> wrote:

Let's do google doc, do we know everyone's email?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/masonshuler/CloudApp/issues/1#issuecomment-372480421>,
or mute the thread
