### ISSUE TITLE
Agree on database schema and fill with sample data

### ISSUE THREAD

**Issue by masonshuler** [masonshuler/CloudApp#2]

**Comment by emcghee** [comment]
Bolded texts means that field should be required.

Tables: User, UserPhoto, Items

User: **id**, **username**, **password hash**, **first_name**, middle_name, **last_name**, **address1**, address2, **city**, **state**, **zipcode**, **security_question**, **security_answer**, **email**, credit_card_number, credit_card_expiration_date, credit_card_security_code, **phone_number**
- We will not store passwords, but only their hash. Will store credit card information so that users can buy items, however it is not required until the user goes to buy something. Phone number and email are required for 2-factor authentication

UserPhoto: **id**, **extension**, **user_id**
- This table is required for users to have their own profile picture.

Items: **id**, **title**, **price**, rating, **category**, **imageUrl**, **userId**, description, date_published
- Date published will be calculated by the back-end, not an option available for the user. Rating will start at No Rating Available until first customer rates that item

**Comment by masonshuler** [comment]
I think this is perfect. However, I don't if we should be storing the credit card information/address for more than the PoS. I think this would add too much time focusing on security. 

@icekreamkuhn what are your thoughts?

**Comment by emcghee** [comment]
So I followed your guys's advice and took out the credit card info. Also it is apparently super easy to use image blobs in SQL so we can do that. I committed the sql file to the root folder and running it in my netbeans it runs with no errors and creates the right database. So all we need to do is come up with sample input.

**Comment by jtkuhn** [comment]
We're tackling this during today's meeting and have modified the .sql file accordingly.
